?start: link

link: "Link(" NUMBER ")" | "Link(" NUMBER "," link* ")" | "Link(" link* ")"
?link_first: "Link("
?link_rest: NUMBER "," link* ")" | link* ")"

%ignore /\s+/
%import common.NUMBER


tree_node: "null"


?label: "null"

branches: "null"

%ignore /\s+/
%import common.NUMBER


rstring: "r\"" regex* "\""

?regex: character | word

character: LETTER | NUMBER
word: WORD

%ignore /\s+/
%import common.LETTER
%import common.NUMBER
%import common.WORD

